### PR TITLE
fix macOS & iOS libs

### LINKED ISSUE #93: [Bug Report] Can't release app on the iOS App Store
Hello,

I've integrated media_kit in an iOS app and when I upload the binary to the iOS App Store, I receive an email saying that my app has an issue : 

> ITMS-90429: Invalid Swift Support - The files libswiftDarwin.dylib, libswiftMetal.dylib, libswiftCoreAudio.dylib, libswiftsimd.dylib, libswiftQuartzCore.dylib, libswift_Concurrency.dylib, libswiftos.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreGraphics.dylib, libswiftCoreData.dylib, libswiftCoreFoundation.dylib, libswiftUIKit.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftMediaPlayer.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/Runner.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

I tried some workarounds I found on StackOverflow like:
- Set "Always Embed Swift Standard Libraries = YES"
- Set "Strip Siwft Symbols = NO"
But I always get the same error message from ASC

Do you know how I can fix it?

### PR DESCRIPTION
**Pull request by birros**
Fix #93

### CODE REVIEW

**Comment by alexmercerind** [comment]
I really appreciate this. It'll be really-really great to ship it.

**Comment by birros** [comment]
Well, the last commt is blocking the install of `ipa` with AltStore, there is a missing `Info.plist` that I need to create, but I have no idea how...

Also, I had to fix the build for the arm64 simulator, whose platform is not the right one set... (https://bogo.wtf/arm64-to-sim-dylibs.html)

Finally, since the last macOS update, I can no longer run Flutter in dev mode on my iPhone…

I've never seen a platform as crappy as Apple. The worst engineers on the planet!

I'm so close to leaving the Apple ecosystem, any action, any dev takes 100 times more time than on Linux!

I'm taking a break, I'm sick of it!

**Comment by birros** [comment]
Ok, now `media_kit_libs_ios_video` and `media_kit_libs_macos_video` use a `.xcframework` instead of libraries.

This allows two things:
- iOS: respects the following App Store rule:
  > Dynamic libraries outside of a framework bundle, which typically have the file extension .dylib, are not supported on iOS, watchOS, or tvOS, except for the system Swift libraries provided by Xcode.
- iOS: allows xcode to select the correct framework depending on the selected device: real (arm64) or simulator (arm64 & x86_64)

I need two tests:
- @JulienDev: Can you check if this fixes the publication to the App Store?
- @HankG: Can you check if this fixes the simulator version under Apple Silicon?

Thx.

**Comment by birros** [comment]
There is a problem with the signature of the libs included in the framework, I have to create as many frameworks as there are libs, that should solve the problem.

**Comment by birros** [comment]
From Discord: @JulienDev no longer has an error when uploading to the App Store, he is waiting for a review 🙂

**Comment by zezo357** [comment]
@birros do you think this may fix my problem?

 The build on Macos and iOS I told you on discord

**Comment by birros** [comment]
> @birros do you think this may fix my problem?

I don't think it's related.

**Comment by zezo357** [comment]
@birros this pr fixed compilation on macos on my side,while nothing changed on ios

**Comment by sbenmeddour** [comment]
I can give you compilation logs or something else for a mac with a M2 chip if you need

**Comment by birros** [comment]
For all those who have difficulty building for iOS: https://stackoverflow.com/questions/75901592/after-upgrading-to-xcode-14-3-while-trying-to-archive-a-flutter-app-i-get-com/75911207#75911207

---

Now that I've been able to test all the configurations and the iOS App Store release looks good, I'm going to move the logic into [birros/libmpv-build](https://github.com/birros/libmpv-build), within 24 hours it should be done.

**Comment by birros** [comment]
Recap:
- migrated the repo responsible for building libmpv for macOS & iOS to the new [media-kit](https://github.com/media-kit) organization
- replaced the use of `.dylib` by `.xcframework`
  - fix mpv loading in arm64 simulator
  - fix #93
- update the minimum version of macOS to 11.0

This new architecture does not fix #98, because it is not related.

**Pull request merged**
