### PR TITLE
Documentation for media_kit

### PR DESCRIPTION
**Pull request by prateekmedia**

### CODE REVIEW

**Comment by alexmercerind** [comment]
Hi! I was wondering, may you take a look at the `Video` controls instead. More may be found at: #114.

I later realized that I should author the documentation myself; since it is going to be the first page that presents the project.

**Comment by prateekmedia** [comment]
Sure

**Comment by alexmercerind** [comment]
I'd like to have some good-looking, neutral, extensible (configurable) controls for the `Video` widget.
I feel code contribution will more more deterministic to you than authoring documentation.

[package:chewie](https://github.com/fluttercommunity/chewie) provides some good default starter controls with good extensibility.

**Comment by zezo357** [comment]
> I'd like to have some good-looking, neutral, extensible (configurable) controls for the `Video` widget, which may be adapted by various kinds of projects & apps. I feel code contribution will more more deterministic to you than authoring documentation.
> 
> [package:chewie](https://github.com/fluttercommunity/chewie) provides some good default starter controls with good extensibility.

https://pub.dev/packages/flutter_meedu_videoplayer does my pacakage help? i am using combination of media kit and video player but when media kit supports web i will convert to it

**Comment by alexmercerind** [comment]
@zezo357

> https://pub.dev/packages/flutter_meedu_videoplayer does my package help?

Are you interested in upstreaming it to package:media_kit, those should go in package:media_kit_video?

I'd need more neutral & configurable set of controls, hopefully after few reviews. I in this sentence reflects this project (not me or my project), whose aim is completion & meeting every media playback related requirement.

>  I am using combination of `media_kit` and `video_player` but when `media_kit` supports web I will convert to it.

I'm unable to understand, what is the motive of the package then? Next 1.0.0 of package:media_kit will ship these gimmicks & abstractions as part of #114, while still offering audio only playback & more low-level API.
Right now your package still serves a purpose, since we don't offer Android & Web yet. Why migrate, deprecate it then.
**You are simply redistributing package:media_kit without giving us proper credit.** Place links & details about package:media_kit at the top of your GitHub & pub.dev README like [package:chewie](https://github.com/fluttercommunity/chewie):

chewie_description_mentioning_video_player

Also, we had similar abstraction of packages, until package:media_kit is fully capable (it's no massive engineering):
https://github.com/bluecherrydvr/unity/tree/main/packages/unity_video_player

**Comment by zezo357** [comment]
> @zezo357
> 
> > https://pub.dev/packages/flutter_meedu_videoplayer does my package help?
> 
> Are you interested in upstreaming it to package:media_kit (those should go in package:media_kit_video)?
> 
> I'd need more neutral & configurable set of controls, hopefully after few reviews. I in this sentence reflects this project (not me or my project), whose aim is completion & meeting every media playback related requirement.
> 
> >  I am using combination of `media_kit` and `video_player` but when `media_kit` supports web I will convert to it.
> 
> I'm unable to understand, what is the motive of the package then? Next 1.0.0 of package:media_kit will ship these gimmicks & abstractions as part of #114, while still offering audio only playback & more low-level API.
> Right now your package still serves a purpose, since we don't offer Android & Web yet. Why migrate, deprecate it then.
> **You are simply redistributing package:media_kit without giving us proper credit.** Place links & details about package:media_kit at the top of your GitHub & pub.dev README like [package:chewie](https://github.com/fluttercommunity/chewie):
> 
> chewie_description_mentioning_video_player
> 
> Also, we had similar abstraction of packages, until package:media_kit is fully capable (it's no massive engineering):
> https://github.com/bluecherrydvr/unity/tree/main/packages/unity_video_player


For the streaming to your package part will think about it and make a pr if decided if I agree?


I already mentioned that I use your package for desktop support at the top of my read me 🤔 don't know what is the problem about credit.

**Comment by alexmercerind** [comment]
- Add hyperlinks to `package:video_player` & `package:media_kit` & mention their names correctly.
- In description, mention `media_kit` instead of `video_player_media_kit`.

It's entirely up to you; your morals & ethics. I don't really care (but you should).
Do you really feel the degree of work is anywhere even 10% of the engineering work done here?

**Comment by zezo357** [comment]
> - Add hyperlinks to `package:video_player` & `package:media_kit` & mention their names correctly.
> - In description, mention `media_kit` instead of `video_player_media_kit`.
> 
> See [package:chewie](https://github.com/fluttercommunity/chewie) for reference.
> 
> It's entirely up to you; your morals & ethics. I don't really care (but you should).
> Do you really feel the degree of work is anywhere even 10% of the engineering work done here?

I already put them as that's what I think is right, but yeah hyper links are better. Thank you, will update it

**Comment by zezo357** [comment]
> - Add hyperlinks to `package:video_player` & `package:media_kit` & mention their names correctly.
> - In description, mention `media_kit` instead of `video_player_media_kit`.
> 
> See [package:chewie](https://github.com/fluttercommunity/chewie) for reference.
> 
> It's entirely up to you; your morals & ethics. I don't really care (but you should).
> Do you really feel the degree of work is anywhere even 10% of the engineering work done here?

For the part of engineering, I am doing a partially customizable ui with features the most people would like to use and if they don't they can disable it, so yeah I think I am doing good of course not the same as your package since you are handling the video playback and ffi. 

Don't know if I answered the question correctly or not here 😅

**Comment by alexmercerind** [comment]
A small portion of work done in package:media_kit :
- Architecture design (for supporting all use-cases e.g. Flutter & Dart; modularizing the project).
- Feasibility study (for making use of ANGLE or libmpv etc.).
- Native interop using platform channels or FFI.
- OpenGL or pixel buffer rendering on each platform.
- ANGLE interop on Windows.
- (Cross-) compiling native libraries.
- Fetching & bundling native libraries.
- Designing & implementing abstracted API for usage in Flutter & Dart.

We're going from ground-up. And everything combined with separate implementation challenges.

I have to implement those features which are part of your project regardless because I hold some degree of obligation & I'm bound to complete requirements of people who are sponsoring this work. Better performance, cross-platform support & stability are the ultimate goal. [[RFC] Goals for 1.0.0](https://github.com/alexmercerind/media_kit/issues/114) provides goals before 1.0.0 & goals after 1.0.0. For now things are restricted to just playback (audio & video).

**Comment by zezo357** [comment]
> A small portion of work done in package:media_kit :
> - Architecture design (for supporting all use-cases e.g. Flutter & Dart; modularizing the project).
> - Feasibility study (for making use of ANGLE or libmpv etc.).
> - Native interop using platform channels or FFI for using texture registrar API & libmpv.
> - OpenGL or pixel buffer rendering on each platform.
> - ANGLE hosting on Windows.
> - (Cross-) compiling native libraries.
> - Fetching & bundling native libraries.
> - Designing & implementing abstracted API for usage in Flutter & Dart.
> 
> We're going from ground-up & taking responsibility of everything.
> 
> I have to implement those features which are part of your project regardless because I hold some degree of obligation & I'm bound to complete requirements of people who are sponsoring this work. Better performance, cross-platform support & stability are the ultimate goal. [[RFC] Goals for 1.0.0](https://github.com/alexmercerind/media_kit/issues/114) provides goals before 1.0.0 & goals after 1.0.0. For now things are restricted to just playback (audio & video).

I know that, and thank you for it

This is why I am using it !? And that's why I mentioned it in the readme since I didn't implement those!

I still don't get why the question was asked 😅

**Comment by alexmercerind** [comment]
> I still don't get why the question was asked.

The question still stands valid. What will be the purpose of that package if the features are implemented within package:media_kit in a better architectured & documented way (after 1.0.0)? Plus... package:media_kit will be able to hold accountability of every single thing.

Informally... if I had time I would've done it already.

**Comment by zezo357** [comment]
> > I still don't get why the question was asked.
> 
> The question still stands valid. What will be the purpose of that package if the features are implemented within package:media_kit in a better architectured & documented way (after 1.0.0)?
> 
> Plus... package:media_kit will be able to hold accountability of every single thing. If I had time I would've done it already.

Got it, the problem is that I can't assure that I follow the same patterns you follow neither did I make it fully customizable.

**Pull request closed without merging**
