### PR TITLE
Major Changes

### PR DESCRIPTION
**Pull request by alexmercerind**
1. Now `Media` can be opened directly.

```dart
await player.open(Media('file:///C:/Users/Hitesh/Music/Sample.mp3'));
await player.open(Media('file:///C:/Users/Hitesh/Video/Sample.mkv'));
await player.open(
  Playlist(
    [
      Media('file:///C:/Users/Hitesh/Video/Sample.mkv'),
      Media('https://www.example.com/sample.mp4'),
      Media('rtsp://www.example.com/live'),
    ],
  ),
);
```

2. Improve `Player`'s internal playlist & state handling.
3. Draw first frame on `Player.open` before `Player.play`.
4. Bump required Flutter version to 3.7.0 in package:media_kit_video.
5. Utilize the unregister texture release callback on Windows. Further improves overall stability.
6. Updated CHANGELOG.
7. [Test application now has test screens in separate individual files](https://github.com/alexmercerind/media_kit/tree/code-cleanup-and-restructure/media_kit_test/lib/tests).
8. New test: [06.paint_first_frame.dart](https://github.com/alexmercerind/media_kit/blob/code-cleanup-and-restructure/media_kit_test/lib/tests/06.paint_first_frame.dart).

### CODE REVIEW

**Comment by alexmercerind** [comment]
Maybe something like `VideoController.waitUntilFirstFrameRendered` can be offered in future.

<hr>

I see this as the release candidate.

**Comment by alexmercerind** [comment]
https://user-images.githubusercontent.com/28951144/228332680-432ebe01-8f53-4f17-a214-d1d78379505d.mp4

**Review by birros — APPROVED** [review]
LGTM!

`06.paint_first_frame.dart` works as expected on macOS and iOS. Awesome!

---

Should I add the iOS & macOS documentation to this pull request, or in another one.

**Comment by alexmercerind** [comment]
> @alexmercerind Should I add the iOS & macOS documentation to this pull request, or in another one.

The root ./README.md on the repository won't be published at pub.dev, but ./media_kit/README.md will be.

Users are going to see the "Brief Start" & "Rendering Video" sections for usage (until there's some good professionally written documentation). I don't think they will dive into inner specifics of the implementation at all.
And... It can be a good exercise for me to draw the class diagrams etc. of the existing macOS/iOS implementation myself + receive your review. I think we can substitute it for now.

<hr>

Let's release v0.0.2 to the community! 🎉 This is really performant & stable.

Everything looks good to me, let me test out few other internal things to make sure everything is polished.
In next release, I aim for:
- Android support.
- Web support.
- Reduced video library size (~30MB without compression on Windows; ~10 MB after LZMA).

**Pull request merged**
