### PR TITLE
added namespace for AGP8 compatibility

### PR DESCRIPTION
**Pull request by deckerst**

### CODE REVIEW

**Comment by alexmercerind** [comment]
Hi @deckerst, thanks a lot.

Have you tested it with AGP8? We're nearing our 1.0.0 release & it's good to have this resolved.

**Comment by deckerst** [comment]
No, not yet. I've just started yesterday evaluating your package for my project. I know that the fix in this PR is safe, but there may be other things to fix for AGP8. For now, I downgraded AGP in my project to move on and tackle other issues.

**Comment by alexmercerind** [comment]
Thanks!

There are a number of new features, fixes & improvements in #250; including highly configurable pre-built video-controls. The [README](https://github.com/alexmercerind/media_kit) is now updated to reflect the new updates & documentation. I hope this adds to your evaluation.

<hr>

<table>
  <tr>
    <td>
      <a href="#materialdesktopvideocontrols"><tt>MaterialDesktopVideoControls</tt></a>
    </td>
    <td>
      <a href="#materialvideocontrols"><tt>MaterialVideoControls</tt></a>
    </td>
  </tr>
  <tr>
    <td>
      
    </td>
    <td>
      
    </td>
  </tr>
</table>

<hr>

**Comment by deckerst** [comment]
Thanks for letting me know. Great to know you actively work on this nice package!

At this stage, I'm mostly checking compatibility. So far, my concerns are AGP8 support, Dart 3 support (for compatibility with other dependencies), and Android content URI support.

**Comment by deckerst** [comment]
Just to confirm that I tested it and that the fix in this PR is enough to make it compatible with AGP8.

**Pull request merged**
