### PR TITLE
[WIP] feat: web support

### PR DESCRIPTION
**Pull request by alexmercerind**
Support for Flutter Web.

The last (but not least) platform package:media_kit didn't have support for. Once this pull-request lands:

| Platform  | Video | Audio |
| --------- | ----- | ----- |
| Android   | ✅ | ✅ |
| iOS       | ✅ | ✅ |
| macOS     | ✅ | ✅ |
| Windows   | ✅ | ✅ |
| GNU/Linux | ✅ | ✅ |
| Web       | ✅ | ✅ |

### CODE REVIEW

**Comment by alexmercerind** [comment]
For the visitors:

There is no implementation in this pull-request yet.

Till now, package:media_kit could not be imported on web. Now it can now be successfully imported & compiled for web. dart:ffi & other implementations which do not support web have been conditionally avoided.

**Comment by alexmercerind** [comment]
The [`package:media_kit_video`](https://github.com/alexmercerind/media_kit/tree/feat/web-support/media_kit_video) implementation for web is complete & rendering works correctly. I don't think there's anything left on that part. FYI: It's using platform view on web.

Implementing the various methods in [`Player` class for web](https://github.com/alexmercerind/media_kit/blob/feat/web-support/media_kit/lib/src/web/player.dart) is left. Let's see what choices & features do we have here as compared to our extremely powerful libmpv/FFmpeg backend for native platforms.
_If you wish to take a look, look-up for `// TODO(@alexmercerind):` comments in code._

image
image
image

**Comment by alexmercerind** [comment]
Wait... `02.single_player_multiple_video.dart` doesn't work, platform view moment.

**Comment by AnonymHK** [comment]
Have you completed the support for Flutter Web?

**Comment by alexmercerind** [comment]
@AnonymHK, not even close. This pull-request needs more work.

Currently all platforms except web are supported. There are some higher priority tasks for us to handle.

**Comment by zq7695zq** [comment]
Have you completed the support for Flutter Web now?

**Comment by alexmercerind** [comment]
Hi @zq7695zq!

I truly understand that this is exciting.

I'm actively working on the project, we should have a stable 1.0.0 release by the end of this month (with web support). For now all the other platforms, Android, iOS, Windows, macOS, GNU/Linux are supported. There are few other important features & house-keeping that I'm doing so that we have a steady ride in the future.

The core goal of project has always been stability & performance. I need to ensure the quality of the code that I put out.

<hr>

If you wish to speed up the progress, you can help us out. Here is the web implementation. I'll be extremely happy to accept PR. On web, we don't have any choice but to use what web browser offers, thus we just need to sort of "copy-paste" things from [`package:video_player_web`](https://github.com/flutter/packages/tree/main/packages/video_player/video_player_web). The code architecture is done, so there aren't any design related challenges:

https://github.com/alexmercerind/media_kit/blob/main/media_kit/lib/src/player/web/player/real.dart

As you can see most methods are unimplemented at the moment.
To utilize this, you'd need to modify few lines to use already available code:

https://github.com/alexmercerind/media_kit/blob/f0f91155900d27e43421fcefcb24793cfd310480/media_kit/lib/src/player/player.dart#L109-L111
https://github.com/alexmercerind/media_kit/blob/f0f91155900d27e43421fcefcb24793cfd310480/media_kit_video/lib/src/video_controller/video_controller.dart#L76-L78

OR... Just wait for some time.

**Comment by zq7695zq** [comment]
@alexmercerind 
I’m sorry, actually, I’ma beginner in flutter, so I can only wait for you to complete the WEB part of the code. Recently, I have been using your library to make an APP to participate in a school competition. Thank you very much for your work!

**Comment by zezo357** [comment]
> Hi @zq7695zq!
> 
> I truly understand that this is exciting.
> 
> I'm actively working on the project, we should have a stable 1.0.0 release by the end of this month (with web support). For now all the other platforms, Android, iOS, Windows, macOS, GNU/Linux are supported. There are few other important features & house-keeping that I'm doing so that we have a steady ride in the future.
> 
> The core goal of project has always been stability & performance. I need to ensure the quality of the code that I put out.
> 
> If you wish to speed up the progress, you can help us out. Here is the web implementation. I'll be extremely happy to accept PR. On web, we don't have any choice but to use what web browser offers, thus we just need to sort of "copy-paste" things from [`package:video_player_web`](https://github.com/flutter/packages/tree/main/packages/video_player/video_player_web). The code architecture is done, so there aren't any design related challenges:
> 
> https://github.com/alexmercerind/media_kit/blob/main/media_kit/lib/src/player/web/player/real.dart
> 
> As you can see most methods are unimplemented at the moment. However, this basic implementation works as you can see in the images above.
> 
> To utilize this, you'd need to modify few lines to use already available code:
> 
> https://github.com/alexmercerind/media_kit/blob/f0f91155900d27e43421fcefcb24793cfd310480/media_kit/lib/src/player/player.dart#L109-L111
> 
> 
> https://github.com/alexmercerind/media_kit/blob/f0f91155900d27e43421fcefcb24793cfd310480/media_kit_video/lib/src/video_controller/video_controller.dart#L76-L78
> 
> OR... Just wait for some time.

https://pub.dev/packages/video_player_web_hls do you think we should integrate this package? since it does allow m3u8 playback, and the official video_player doesnt.

**Comment by alexmercerind** [comment]
Both statements incorrect.

**Comment by alexmercerind** [comment]
The stable web support is now available (with ton of other features & stability improvements) in [`package:media_kit` 1.0.0](https://github.com/alexmercerind/media_kit/releases/tag/media_kit-v1.0.0).

```yaml
dependencies:
  media_kit: ^1.0.0                              # Primary package.
  
  media_kit_video: ^1.0.0                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.5            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

Refer to the README for updated project guide.

**Pull request merged**
