### PR TITLE
feat : select video, audio, sub tracks

### PR DESCRIPTION
**Pull request by JulienDev**
* Listen to tracks changed for playing media
* Select video/audio/sub track
* Get current video/audio/sub track

You can test the feature by using this video URI : https://github.com/ietf-wg-cellar/matroska-test-files/raw/master/test_files/test5.mkv

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks for rebase 🙏

**Comment by JulienDev** [comment]
Let me just check that's working again :D

**Comment by JulienDev** [comment]
All good, I'll let you review the code, feel free to make changes :)

**Comment by JulienDev** [comment]
I'll add a way to get selected tracks later today

**Comment by JulienDev** [comment]
I'm done with my PR @alexmercerind

**Comment by birros** [comment]
I am inspecting this pull request, and I think it would be better to add 6 new states:
```dart
List<Track> audioTracks
List<Track> videoTracks
List<Track> subTracks
Track audioTrack
Track videoTrack
Track subTrack
```

And the 6 corresponding streams, listening to the `track-list` & `current-tracks` events.

@alexmercerind What do you think?

**Review by alexmercerind — CHANGES_REQUESTED** [review]

**Comment by alexmercerind** [comment]
Closing this in favor of #83. A large number of implementation & design changes.

**Comment by alexmercerind** [comment]
I'm open to feedback.

**Pull request closed without merging**
