### PR TITLE
feat: UI controls for Video widget

### PR DESCRIPTION
**Pull request by zezo357**
Added controls based on chewie with changes to allow it to work with media_kit

@AhmedAbouelkher can you check if thats same as we discussed or not? and if you have any changes let me know.

image

## TODO

- logic
  - [x] fix missing mouse cursor on some buttons
  - [x] add (real) full-screen support on desktop (`window_manager`)
  - [x] check visibility when white video is played
- extra (to discuss)
  - [x] If possible, and if it doesn't require too much refactor, remove the dependency on `Provider`
  - [ ] use a menu / popover instead of a bottom sheet (like YoutTube, iOS player…)
  - [ ] add touch friendly shortcuts
- doc
  - [ ] update pubspec.yaml description
  - [ ] add README content
  - [ ] add example

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks for the pull-request, we will  make sure to get it over the line.

There are few concerns visually, which is understandable as this is initial work. The PR is really good & helpful.

The slider looks slight off to me (personally) & background becoming transparent on some aspect ratios.

We had this [`showControls` argument in `Video` widget of `package:dart_vlc`](https://github.com/alexmercerind/dart_vlc/blob/2901b19cc838c857b6636916529e46f74fca9b5f/lib/src/widgets/video.dart#L89). My idea is to have similar here. Controls enabled by default, like in any normal web browser, minimal by default & extensible when needed.

Also, one more thing I'd like to mention (as you have possibly seen), we are being kind of "picky" with the code, implementation & design. Both me & @ birros review each other's code before landing it. This is important because we want the best possible feature-proof & future-proof API & implementation. I hope the finalized result will also match the requirements of your own project(s).

Thanks again!

**Comment by zezo357** [comment]
> The slider looks slight off to me (personally) & background becoming transparent on some aspect ratios.

Can you elaborate more on how they should look like.



For the show controls, I will integrate it in video widget then.

**Comment by AhmedAbouelkher** [comment]
> The slider looks slight off to me (personally) & background becoming transparent on some aspect ratios.

The issue is due to the video aspect ratio, but the video controls are placed correctly.

We are currently working on the video controls UI, thus every suggestion will be welcomed.

**Comment by birros** [comment]
Thanks for the initiative guys! This first iteration is pretty clean (modulo some display issues).

---

But I am not fan with the idea of putting this code in `media_kit_video`, I know I'm being annoying with it, but the current code of this package (main branch) will never call the code about the controls. This means that the controls code can (must) be moved to a separate package.

It should be optional like `media_kit_native_event_loop`, and depend on `media_kit` & `media_kit_video`.
Maybe `media_kit_video_controls`???

```tree
.
├─ media_kit_video
│  └─ Video
└─ media_kit_video_controls
   └─ Video
```

@alexmercerind what's your opinion?

---

@zezo357 @AhmedAbouelkher Concerning display issues, make sure the controls are visible on white and black backgrounds. YouTube is the best reference in my opinion, they use a combination of black outlines and shadows.

**Comment by zezo357** [comment]
new look
image

image

**Comment by birros** [comment]
I've cleaned up the PR a bit, and added a TODO section to the main post above.
The ones about the doc (example + README + pubspec description) can be put aside for now, they will be updated by a maintainer before the merge.

**Comment by zezo357** [comment]
`check visibility when white video is played`
white background doesnt affect visibility 
image

**Comment by damywise** [comment]
Does/will this control widgets support audio and/or will there be a separate package that supports audio controls?

**Comment by zezo357** [comment]
> Does/will this control widgets support audio and/or will there be a separate package that supports audio controls?

These controls allow only mute and unmute for now. 


Will it support volume changes in general? I don't know if the maintainers want it or not

**Comment by Quackdoc** [comment]
sorry, been super inactive as lots of things have cropped up for me lately, personally I would like to see a volume widget with audio control on the desktop and browser platforms. I don't think it's a stretch to assume that most people will want some kind of volume adjustment on desktop, on mobile I'm not too sure since I don't really work much on that end of things.

from a code perspective I haven't looked over it much, but I would at least like to see some comments, especially with the code blocks that are commented out should have some explanations, also make sure to note any TODOs.

**Comment by zezo357** [comment]
Yes will do when I got time

**Comment by zezo357** [comment]
> @zezo357 can you rebase this to main branch?

done

**Comment by zezo357** [comment]
may i ask why were this pr closed?

**Comment by Prince-of-death** [comment]
you can make this a seperate package on pub.dev where we wrap the orginal media kit player with your widget. Can you lease do that. You can then ask the devs to link it in the readme

**Comment by alexmercerind** [comment]
The code in this pull request is trash. The code sample (you can read) in this PR is something I'd never like to write.

I'm working on my own controls, which will be:
- Better implemented.
- Better looking.
- Having better API.

**Comment by alexmercerind** [comment]
One of our sponsors needs built-in video controls. And... that is one thing which is holding us back from 1.0.0.

I like quality & stability. We should be there by the end-of month.

**Comment by zezo357** [comment]
> you can make this a seperate package on pub.dev where we wrap the orginal media kit player with your widget. Can you lease do that. You can then ask the devs to link it in the readme

Already done that, you can find it in my GitHub profile, and published to pub.dev flutter_meedu_videoplayer

**Comment by zezo357** [comment]
> The code in this pull request is trash. The code sample (you can read) in this PR is something I'd never like to write.
> 
> I'm working on my own controls, which will be:
> - Better implemented.
> - Better looking.
> - Having better API.

Thank you for your harsh words, all I did is follow chewie like you asked....

Anyway hope the best of luck for you.

**Comment by zezo357** [comment]
For the sake of my future self, can you provide a sample or documentation of what the best practices you follow?


Since the sample you sent from my code was the same as your example added one widget and an if condition, so I don't know what is wrong with that

**Comment by alexmercerind** [comment]
The dislikers of my comment above: @mount33 @gibahjoe, the last version ships my implementation of video controls.

You can [see screenshots in the README](https://github.com/alexmercerind/media_kit#platforms) or [play around with them on the web](https://[alexmercerind.github.io/media_kit/#/).

They are highly-customizable, follow the same design principles as Flutter (`Theme` & `ThemeData`), look beautiful & very identical to YouTube's in terms of design.

I, unfortunately, have a thing for writing good code & releasing only quality stuff.

**Comment by gibahjoe** [comment]
> The dislikers of my comment above: @mount33 @gibahjoe, the last version ships my implementation of video controls.
> 
> You can [see screenshots in the README](https://github.com/alexmercerind/media_kit#platforms) or [play around with them on the web](https://alexmercerind.github.io/media_kit/#/).
> 
> They are far-far easier to use (friendly API), highly-customizable, follow the same design principles as Flutter (`Theme` & `ThemeData` etc.), look beautiful & very identical to YouTube's in terms of design.
> 
> Docs: https://github.com/alexmercerind/media_kit#video-controls
> 
> I, unfortunately, have a thing for writing good code & releasing only quality stuff.

Which is fine. You just don't have to be condescending about it and calling the PR trash.

**Comment by niklaskorz** [comment]
I'm at a loss of words considering the toxicity of this repository's maintainer towards volunteering open source contributors, who at the very least are doing pull requests like these to learn, and in the best case want others to benefit from their contribution.

@alexmercerind must be very well aware by now, considering the feedback he got, that this kind of response is unacceptable. Nonetheless, I find this quote from The Social Network very fitting and hope you take it to your heart:

> You are probably going to be a very successful computer person. But you're going to go through life thinking that girls don't like you because you're a nerd. And I want you to know, from the bottom of my heart, that won't be true. It'll be because you're an asshole.

**Comment by alexmercerind** [comment]
@niklaskorz @gibahjoe

This is a community project now (since movement from alexmercerind/media-kit -> media-kit/media-kit).

There's a code of conduct in place:

- #589 

<hr>

How I would've responded 6 months ago to your arguments:

> I'm at a loss of words considering the toxicity of this repository's maintainer towards volunteering open source contributors, who at the very least are doing pull requests like these to learn, and in the best case want others to benefit from their contribution.
> 

FYI: I'm also a volunteer who devoted 100s of personal hours to this project.

This is my project, in my repository on my account. Why do I have to obey any rules about what happens in my repository?

I have [worked extremely hard on this project to make it possible (as an volunteer)](https://github.com/media-kit/media-kit/graphs/contributors). The work in this project is no joke (you are free to have your opinion) in terms of size, complexity, design & implementation etc.

Especially when working on a library, which you expect to be used by multiple dependents, you just can't compromise on the quality. If you can't see the problems in the public API this pull-request introduces, I'm not sure what to say. For reference, take the stable implementation which I later landed on `main`.

I know I should've been thankful to the incoming pull-request. However:
I would much rather write my own code & move fast with an implementation I'm more satisfied with, instead of teaching or guiding someone through ~10 code reviews (when I'm already working on this side-project with an extreme lack of time). You also need to consider the fact **the amount of effort a pull-request is going to take** vs. **the amount of effort a fresh implementation would take**. The moment a PR gets merged, it's no longer your problem, it becomes mine.

I use GitHub only to place my code. The only thing I care about is the quality of the code that I author. Comments & social interactions (like this comment) take time. If I didn't choose to make the decisions I made back then, sadly project would've never been where it is right now in such a short time. Sometimes you gotta move fast without compromising on quality & close the pull-request with single line feedback (I don't have HR team to craft a positive sounding feedback).

**Pull request closed without merging**
