### PR TITLE
docs: improve quality

### PR DESCRIPTION
**Pull request by alexmercerind**
It (finally) feels neat.

### CODE REVIEW

**Review by birros — APPROVED** [review]
Perfect!

Just a note on the controls section:
`AdaptiveVideoControls` uses `MaterialVideoControls` and `MaterialDesktopVideoControls` or just `MaterialVideoControls`?

This section is confusing. I think the following schema would be more relevant, but I may be wrong:
```
AdaptiveVideoControls
├── MaterialVideoControls
│   ├── MaterialMobileVideoControls
|   └── MaterialDesktopVideoControls
└── CupertinoVideoControls
```

**Comment by alexmercerind** [comment]
The design philosophy is very similar to how Flutter does it:
- Providing `XYZTheme` & `XYZThemeData`.
- Providing `XYZ.adaptive()`.

I'd need your second approval; still kind of looking around.

**Comment by alexmercerind** [comment]
Also... I added more sections now. I think this "Guide" is good; covers most things.

**Comment by alexmercerind** [comment]
ping: @birros 

I want your second review. Please feel free to add/remove whatever you want. I feel this new "Guide" is good.

And... may you please update the screenshots for iOS & macOS (in README & `media_kit/screenshots`).

#250 has the relevant updates; following up there.

Thanks!

**Review by birros — APPROVED** [review]
LGTM!

**Pull request merged**
